### PR TITLE
CLI commands of Lift

### PR DESCRIPTION
**Pull request by janpio**

### CODE REVIEW

**Comment by janpio** [comment]
Missed anything @divyenduz?

**Comment by divyenduz** [comment]
I think that down takes an argument if we want to show that :)

**Comment by janpio** [comment]
> Same options and arguments as `prisma2 lift up`

?

Or additional ones?

**Comment by divyenduz** [comment]
You can pass `prisma lift down <n>` where `n` is the number of migrations to revert.

**Comment by matthewmueller** [comment]
looks good, please resolve conflicts :-)

**Comment by janpio** [comment]
Fixed and ready for merge again @matthewmueller

**Comment by matthewmueller** [comment]
thanks!

**Pull request merged**
