### PR TITLE
Consolidate binaries spec

### PR DESCRIPTION
**Pull request by divyenduz**
Incorporates the feedback from https://github.com/prisma/specs/issues/62

[Rendered view](https://github.com/prisma/specs/blob/binaries_feedback/binaries/Readme.md)

**Changes introduced by this spec:** 

1. New API to override CLI binary resolution https://github.com/prisma/prisma2/issues/337
2. Rename downloaded binaries for CLI to have the platform specific name https://github.com/prisma/prisma2/issues/366
3. Rename `platforms` to `binaryTargets` and `pinnedPlatform` to `pinnedBinaryTarget` to avoid future SEO collision with "Prisma Platform"

**WIP Working Notes:**

>  Transport (FFI/HTTP)
- Holding off on writing about this for now, Tim+Julius's work would change this for migration engine and is also moving some function from migration engine to query engine. Need to sync with them. 

> Platform overriding/fallback for CLI install
- Requires two environment variables (depending on commands required), this is simpler mental model though than alternatives. 
- Alternatives
-- specifying platform as an env var
-- specifying a folder as an env var with naming convention for binaries and respective CLI command can pick the correct one with some heuristics. 

> Make more consistent
- Done via 
-- introducing CLI/Generate time download notes
-- noting when these respective binaries are used
-- mapping configuration around these concepts

>  Generator: Link to generator spec for binary dependencies
- There is a placeholder for this, once the generator spec is ready, that can be linked. 

> Error handling
- This spec mentions the overview of error handling in the sense of broad handling of errors by throwing/error message. 
- Does detailed error handling (wrt wording etc on specific platforms) belong in the same spec?

### CODE REVIEW

**Comment by schickling** [comment]
Still to adjust:

- [ ] Incorporate linux distro dimension into pre-built binaries

**Comment by divyenduz** [comment]
Questions: 

- What would be the naming convention for the ubuntu binaries?

**Comment by divyenduz** [comment]
Proposed changes by Tim: 

- [ ] `binaryTargets` env vars should not be allowed, that makes `pinnedBinaryTarget` vs `bianryTarget` check at CLI time complicated. 

- [ ] `pinnedBinaryTarget` can have custom binary that is not listed in `binaryTargets`, Making this configuration possible

```
binaryTargets = []
pinnedBinaryTargets = "./custom-binary-path"
```

```
pinnedBinaryTargets = "./custom-binary-path"
```

However, for known binaries, `binaryTargets` is required, so, this configuration is not possible

```
pinnedBinaryTargets = "prisma-darwin"
```

**Comment by schickling** [comment]
We decided `pinnedBinaryTarget` is going away in favor of `PRISMA_QUERY_ENGINE_BINARY`.

**Comment by divyenduz** [comment]
This comment represents the latest state and incorporates feedback from all previous messages.

[Rendered View](https://github.com/prisma/specs/blob/binaries_feedback/binaries/Readme.md)

Remaining open questions: 

- [ ] Does the naming convention for Ubuntu 16 binary look good? 

Feedback please 🙏

**Pull request merged**
