### PR TITLE
Studio: State persistence

### PR DESCRIPTION
**Pull request by madebysid**
Rendered view: https://github.com/prisma/specs/blob/feature/studio-persistence/studio/state-persistence.md

### CODE REVIEW

**Comment by janpio** [comment]
This should probably live in `studio/state-persistence.md`. Could you move it and make sure this is good to be merged @madebysid? Thanks.

**Comment by madebysid** [comment]
@janpio Was pretty outdated as well, updated it! Let me know if the format is okay

**Comment by janpio** [comment]
Yes thanks! 

What are the next steps here? Does this still needs review from someone or can this just be merged?

**Comment by madebysid** [comment]
This needs a review from @schickling (mainly the public studio.json API)

**Comment by janpio** [comment]
@schickling says to just merge this

**Pull request merged**
