### PR TITLE
Fix Explicit Many-to-Many

### PR DESCRIPTION
**Pull request by matthewmueller**
This is the plan for many-to-many right?

cc @mavilein @sorenbs

### CODE REVIEW

**Comment by mavilein** [comment]
Yeah basically. Just 2 minor comments:
* You would be free to use either `@@id` or `@@unique`.
* To make this defintion perfomant you would have to use `@@index([blog])`. Otherwise queries that only use the blog column can't use an index.

**Comment by matthewmueller** [comment]
> To make this defintion perfomant you would have to use @@index([blog]). Otherwise queries that only use the blog column can't use an index.

Can you expand on this? Doesn't `@@id` or `@@unique` created an index?

**Comment by mavilein** [comment]
Yes `@@id([author, blog])` adds an index. But this is a composite index that comes with special rules:
* It will be used by the database if the query uses the `author` and `blog` column.
* It will be used by the database if the query uses just the `author` column.
* It will **not** be used by the database if the query uses just the `blog` column.

This is just how composite indexes work. The introduction in this [article](http://www.mysqltutorial.org/mysql-index/mysql-composite-index/) explains this a bit.

But we want to be able to efficiently query even if we are just using the `blog` column. Hence we need to add an index for it.

**Comment by matthewmueller** [comment]
Ahh TIL! Okay I'll make a note of this

**Comment by matthewmueller** [comment]
made a private todo to fix this next week, merging for now since i need to show this to a user.

**Comment by matthewmueller** [comment]
```
model BlogWriter {
  blog      Blog
  author    Writer
  is_owner  Boolean
  @@id([author, blog])
  @@index([blog])
}
```

@mavilein is this correct? Couldn't we attach the index to the blog directly?

```groovy
model BlogWriter {
  blog      Blog @index
  author    Writer
  is_owner  Boolean
  @@id([author, blog])
}
```

**Comment by mavilein** [comment]
@matthewmueller : Yes this is correct. The single field `@index` was intentionally not made part of the spec a long time ago. Would not be a big problem to add it though 🤷‍♂

**Pull request merged**
